name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Continuous Integration ${{ matrix.build_type }} ${{ matrix.toolset_name }}
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        toolset: [v142, ClangCL]
        include:
          - toolset: v142
            tooset_name: MSVC
          - toolset: ClangCL
            tooset_name: clang-cl

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -A x64 -T ${{ matrix.toolset }}

      - name: Build
        run: |
          cd build
          cmake --build . --config ${{ matrix.build_type }} --target ALL_BUILD
